training:
  lr: 0.03
  weight-decay: 0.0000001
  bs: 128
  scheduler: 'steplr'
  gamma: 0.5
  step-size: 25
  workers: 4
  q_size: 2048
  T: 0.07
  M: 0.995

model:
  h_dim: 256
  o_dim: 256
  depth: 4
  dropout: 0.1