training:
  lr: 0.001
  weight-decay: 0.0001
  bs: 128
  workers: 0
  scheduler: 'steplr'
  gamma: 0.5
  step-size: 25
  q_size: 4096
  T: 0.2
  M: 0.995
  lambda: 0.5

model:
  h_dim: 128
  o_dim: 128
  depth: 2
  dropout: 0.1