training:
  lr: 0.00001
  weight-decay: 0.0001
  bs: 16
  workers: 0
  scheduler: 'steplr'
  gamma: 0.5
  step-size: 25
  q_size: 1024
  T: 0.2
  M: 0.999
  lambda: 0.5

model:
  h_dim: 256
  o_dim: 128
  depth: 2
  dropout: 0.1