training:
  lr: 0.001
  weight-decay: 0.0000001
  bs: 32
  scheduler: 'steplr'
  gamma: 0.5
  step-size: 25
  workers: 4
  q_size: 1024
  lambda: 0.5

model:
  h_dim: 256
  o_dim: 256
  depth: 4
  dropout: 0.1
  T: 0.2