training:
  lr: 0.00001
  weight-decay: 0.0005
  bs: 8
  scheduler: 'reducelr'
  gamma: 0.5
  step-size: 50
  embed_model: 'sentence-transformers/all-MiniLM-L6-v2'

model:
  h_dim: 256
  head: 8
  t_dropout: 0.2
  g_dropout: 0.3
  v_dropout: 0.2
  a_dropout: 0.2
  use_cross_modal: False